### ISSUE TITLE
any news  about the website with more extensive documentation?

### ISSUE THREAD

**Issue by vincentclaes** [datamindedbe/lighthouse#13]
we could use it :p

**Comment by peeterskris** [comment]
Vincent, shame on us for not publishing the documentation sooner. And also shame on us for not replying sooner. This is now a "thing" and we'll do our very best to help you get started. I know it's not a trivial library without documentation.

**Comment by peeterskris** [comment]
@vincentclaes we now have a tutorial https://datamindedbe.github.io/lighthouse/tutorial/ and a concepts page https://datamindedbe.github.io/lighthouse/concepts/ up. It's not 100% done yet. But I hope it unblocks you. Get in touch if you have more questions. Thanks for being an early adopter.

**Comment by vincentclaes** [comment]
thanks @peeterskris ! we will go through it and come back to you if we have any further questions
